### ISSUE TITLE
Use 'docker compose' command (without hiphen)

### ISSUE THREAD

**Issue by naub1n** [konstruktoid/ansible-role-docker-rootless#204]
Hi,

Docker compose installation is not the same as [Official docker compose installation](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually).

`docker compose` command don't work.
```
docker: 'compose' is not a docker command.
See 'docker --help'
```

But 'docker-compose' command work well.

I add a task to create docker plugins directory and I change the destination path when downloading docker-compose:
```
- name: Create docker plugins directory
  file:
    path: "{{ docker_user_info.home }}/.docker/cli-plugins"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Download docker-compose
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_release }}/docker-compose-linux-x86_64"
    dest: "{{ docker_user_info.home }}/.docker/cli-plugins/docker-compose"
    checksum: sha256:{{ docker_compose_release_shasum }}
    owner: "{{ docker_user }}"
    mode: "0755"
  when: docker_compose
  tags:
    - docker-compose
```

Now I can use `docker compose` command.
