### ISSUE TITLE
Add daemon.json config

### ISSUE THREAD

**Issue by naub1n** [konstruktoid/ansible-role-docker-rootless#224]
Hi !

I have a new request 🙂

Is it possible to create config file daemon.json ?
Example:
```
vars:
  docker_daemon_config:
    data-root: /app/docker
    dns:
      - 8.8.8.8
      - 8.8.4.4
tasks:
    - name: Create daemon.json config file
      copy:
        dest: "/home/{{ docker_user }}/.config/docker/daemon.json"
        content: "{{ docker_daemon_config | to_nice_json }}" 
      notify:
        - Restart rootless docker
```
Thx !
