### ISSUE TITLE
rootless Docker configuration file not installed when docker_rootful is true

### ISSUE THREAD

**Issue by r3mi** [konstruktoid/ansible-role-docker-rootless#578]
Hello,
thanks for this very useful Ansible role !
I have a custom `daemon.json.j2` (with custom `default-address-pools`), but it is not installed for docker-rootless.

Some vars:
```yaml
      docker_daemon_json_template: roles/docker/templates/daemon.json.j2
      docker_rootful_enabled: false
      docker_rootful: true
```

docker rootless is installed ok (`docker context show`== `rootless`).
But my custom configuration is only installed in the global `/etc/docker/daemon.json`. It is absent from `"{{ docker_user_info.home }}/.config/docker/daemon.json"`. Indeed, `docker info` shows that my custom configuration is missing.

Ansible extract with '-vv'
```
TASK [konstruktoid.docker_rootless : Add rootless Docker configuration file] ****************************************************************************
task path: /home/ubuntu/.ansible/roles/konstruktoid.docker_rootless/tasks/docker_install_rootless.yml:89
skipping: [localhost] => {"changed": false, "false_condition": "not docker_rootful", "skip_reason": "Conditional result was False"}
```

**Comment by konstruktoid** [comment]
Hi! 
Thanks for using the role, and yes, that's a bug.

It should probably check if rootful is enabled and not installed.

Will fix it later this evening.

**Comment by konstruktoid** [comment]
Hmm,
did you perhaps install using `docker_rootful: true`?


https://github.com/konstruktoid/ansible-role-docker-rootless/blob/main/tasks/main.yml#L45-L51
```yaml
- name: Install and configure rootless Docker
  ansible.builtin.import_tasks:
    file: docker_install_rootless.yml
  when:
    - not docker_rootful
  tags:
    - docker_rootless
```
